### PR TITLE
Change `deploy` to `publish` to match task name when publishing via NPM.

### PR DESCRIPTION
**Pull request by rpocklin**
The README.md would need to be updated too in the sibling repo `https://github.com/markdalgleish/bespoke.js/blob/master/README.md`

### CODE REVIEW

**Comment by hsablonniere** [comment]
Hey @rpocklin!

Can you explain a bit more what your PR brings? I'm a bit confused. What do you think @mojavelinux?

**Comment by mojavelinux** [comment]
Since we're in the npm ecosystem, and the npm command to publish a module is `npm publish`, I think the idea is to match that terminology for our task that publishes to GitHub. I'd even add that "publish" is the more correct term to use here anyway, as we are "publishing content" not deploying it.

We could rename it, then make deploy depend on publish for backwards compatibility with existing scripts.

**Comment by hsablonniere** [comment]
@rpocklin @mojavelinux Do we really need backward compatibility since it's a v3?

**Comment by mojavelinux** [comment]
I won't cast a vote for the deploy alias. I was just mentioning it's still possible.

**Comment by hsablonniere** [comment]
Fixed in #38 (https://github.com/bespokejs/generator-bespoke/pull/38/commits/3859a17664a36eb5a5bdcb49c4dc3240527cd7c1).

**Comment by mojavelinux** [comment]
This has been implemented in 3.0.0.

**Pull request closed without merging**
