### PR TITLE
make pdf default (and remove dl warning) if nw is cached

### PR DESCRIPTION
**Pull request by davidmarkclements**
:)

### CODE REVIEW

**Comment by davidmarkclements** [comment]
just to explain - it takes a while to check whether nw is cached* so the cache check happens in
parallel to the prompts. So hopefully, but putting pdf Q at the end, for general use on a fair connection the cache check won't even be noticeable.

* in order to check the cache for nw, we need a version number. version number is determined by nw-shot which is a dependency of bespoke-to-pdf which is a dependency of bespoke-pdf. Essentially the version of nw.js is determined by bespoke-pdf. You can't just install and see, because this will trigger the nw.js download - so I created traverse-packages that does recursive "npm view" in order to extract the "nw" field of nw-shot (which holds the relevant nw.js version).

**Comment by markdalgleish** [comment]
This is failing on Travis CI at the moment. Can you look into this?

**Comment by davidmarkclements** [comment]
hmm okay will look into - just need to get a moment

**Comment by davidmarkclements** [comment]
ok fixed 

and also squashed

**Comment by markdalgleish** [comment]
I'm a bit concerned that there are race conditions in both the generator and the test.

Is it possible to prompt only after the NW check has been performed?

Can the test mock out the async dependencies so that it doesn't contain an arbitrary 3500ms timeout?

**Comment by davidmarkclements** [comment]
the race condition in the generator is a trade off against waiting time for the user - if prompt after nw check the user could have anything up to a 3 second wait (given we keep the three second timeout) - is that preferred versus a background check with fallback?

the timeout in the test isn't completely arbitrary it's related to the 3 second timeout (+ 500ms to amply account for processing variance) - but sure we could mock the async deps

It's not ideal, I was thinking of an alternative approach - npm shrinkwrap bespoke-pdf, and find out the version of nw specified in nw-shot. However, .. obviously .. shrinkwrap only includes deps not additional fields. So then I thought, what about putting the desired NW.js version as an optional dependency - one that should break, would it appear in npm-shrinkwrap.json then? ... No, because this: https://github.com/npm/npm/issues/2679  

So.. these are the options I can see

1) keep as is (but mock async deps for test)
2) make user wait for check in CLUI - (feels clunky)
3) figure out a third way

**Comment by hsablonniere** [comment]
Hi @davidmarkclements.

As you can see in #36, we're removing PDF generation in the next version of the generator. We want to push authors to use more up-to-date tools like [astefanutti/decktape](https://github.com/astefanutti/decktape). That's why I'm closing this issue. Let me know your opinion about this. Are you still working on [bespoke-pdf](https://github.com/davidmarkclements/bespoke-pdf)?

**Pull request closed without merging**
